name: cary_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - plotly
  - ca-certificates
  - openssl
  - jupyterlab
  - pandas
  - certifi
  - requests
  - matplotlib
  - seaborn
  - numpy
  - openpyxl
  - polars
  - scikit-learn
  - ipympl
  - nodejs
  - statsmodels
  - ruff
platforms:
  - win-64
  - linux-64
  - osx-64
  - osx-arm64
